name: Flutter CI

on:
  push:
    branches:
    - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '17.x'
    
    - uses: subosito/flutter-action@v1
      with:
        channel: 'beta'
    
    - run: flutter pub get
    
    - run: flutter build apk --split-per-abi --release
    
    - uses: r0adkll/sign-android-release@v1
      name: Sign app APK
      id: sign_app
      with:
        releaseDirectory: build/app/outputs/apk/release
        signingKeyBase64: ${{ secrets.KEYSTORE_BASE64 }}
        alias: ${{ secrets.KEYSTORE_KEY_ALIAS }}
        keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
        keyPassword: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
      env:
        BUILD_TOOLS_VERSION: "30.0.3"
    
    - name: Upload APK as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: signed-apk
        path: build/app/outputs/apk/release/*-signed.apk

    - name: Pre-Release
      if: github.ref == 'refs/heads/master'
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: build/app/outputs/apk/release/*-signed.apk
        tag_name: nightly
        prerelease: true
